### ISSUE TITLE
Rename pipeline parameters for better organization on the DSP run page

### ISSUE THREAD

**Issue by MichaelClifford** [opendatahub-io/ilab-on-ocp#125]
There are a lot of parameters needed for the ilab pipeline, and they are each individually relevant to the SDG, Training or Eval steps. However, the parameter names provide no hint to the users as to what part of the pipeline they control. Furthermore, DSP automatically displays them in alphabetical order. This is simply confusing and not a good user experience. See image below for an example.

We should rename all the params with an appropriate prefix (`sdg_`, `train_`, `eval_mtbench_`, and `eval_final_`) so that they will be group logically on the "Create Run" page.      

<img width="728" alt="Screenshot 2024-10-24 at 10 48 29 AM" src="https://github.com/user-attachments/assets/731fe011-4182-4516-8a01-403060d801fa">

**Comment by tumido** [comment]
I addition we can use the docstring parser of the DSL to populate description. It's not much but it can help.

https://www.kubeflow.org/docs/components/pipelines/user-guides/components/additional-functionality/#component-docstring-format

```python
@dsl.pipeline(display_name='Test pipeline')
def pipeline(
    sdg_foo: str,
    train_baz: str,
):
    """This is a test pipeline.

    Args:
        sdg_foo: This is an SDG parameter Foo that does Bar.
        train_baz: This is a Training parameter Baz that does Qux.

    """
    ...
```

Which translates to IR YAML:

```
pipelineInfo:
  description: This is a test pipeline.
  displayName: Test pipeline
  name: pipeline
root:
  dag:
    ...
  inputDefinitions:
    parameters:
      sdg_foo:
        description: This is an SDG parameter Foo that does Bar.
        parameterType: STRING
      train_baz:
        description: This is a Training parameter Baz that does Qux.
        parameterType: STRING
```

Which is surfaced as following in RHOAI:

![image](https://github.com/user-attachments/assets/62ccf0b2-9010-4ffc-8779-343330b44b70)
